-- Migration: Add Circular Publishing and Notifications Support

-- 1. Update circulars table to support document attachments
ALTER TABLE circulars ADD COLUMN IF NOT EXISTS document_url TEXT;

-- 2. Create notifications table for in-app notifications
CREATE TABLE IF NOT EXISTS notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_username TEXT REFERENCES users(username) ON DELETE CASCADE,
  title TEXT NOT NULL,
  message TEXT NOT NULL,
  is_read BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Enable RLS on notifications
ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;

-- 4. Create policy for notifications (users can only see their own)
CREATE POLICY "Users can view own notifications" 
ON notifications FOR SELECT 
USING (user_username = current_setting('app.current_user', true));

-- For the app to work with anon role, we need a permissive policy
CREATE POLICY "Enable access for all users" 
ON notifications FOR ALL 
USING (true) 
WITH CHECK (true);

-- 5. Create index for faster queries
CREATE INDEX IF NOT EXISTS idx_notifications_user ON notifications(user_username);
CREATE INDEX IF NOT EXISTS idx_notifications_unread ON notifications(user_username, is_read);
