-- 1. Reset Tables (Clean Slate)
drop table if exists leave_requests;
drop table if exists users;

-- 2. Create Users Table
create table users (
  username text primary key,
  password text not null,
  role text not null check (role in ('student', 'staff', 'hod', 'principal')),
  name text not null,
  section text check (section in ('A', 'B')), -- Only relevant for students
  email text -- Added email column
);

-- 3. Create Leave Requests Table
create table leave_requests (
  id bigint generated by default as identity primary key,
  student_username text references users(username),
  student_name text not null,
  student_section text not null,
  leave_type text not null,
  leave_dates text,
  reason text,
  file_url text,
  status text default 'Pending Staff',
  staff_comment text,
  hod_comment text, 
  principal_comment text,
  date_requested timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Enable RLS
alter table users enable row level security;
alter table leave_requests enable row level security;

-- 5. Create Permissive Policies (Relies on App Logic)
create policy "Public Access Users" on users for all using (true) with check (true);
create policy "Public Access Requests" on leave_requests for all using (true) with check (true);

-- 6. Seeding Data

-- Seed Staff, HOD, Principal
insert into users (username, password, role, name, section, email) values
('staff_a', 'staff123', 'staff', 'Staff Member (Section A)', 'A', 'staff_a@college.edu'),
('staff_b', 'staff123', 'staff', 'Staff Member (Section B)', 'B', 'staff_b@college.edu'),
('hod', 'hod123', 'hod', 'Head of Department', null, 'hod@college.edu'),
('principal', 'principal123', 'principal', 'Principal', null, 'principal@college.edu');

-- Seed Students using a loop (Postgres specific)
do $$
begin
  -- Section A Students (1 to 46)
  for i in 1..46 loop
    insert into users (username, password, role, name, section, email)
    values (
      'student_a_' || i, 
      'pass123', 
      'student', 
      'Student A-' || i, 
      'A',
      'student_a_' || i || '@student.college.edu'
    );
  end loop;

  -- Section B Students (1 to 46)
  for i in 1..46 loop
    insert into users (username, password, role, name, section, email)
    values (
      'student_b_' || i, 
      'pass123', 
      'student', 
      'Student B-' || i, 
      'B',
      'student_b_' || i || '@student.college.edu'
    );
  end loop;
end;
$$;
